### ISSUE TITLE
Latest commit deleted all of the rules

### ISSUE THREAD

**Issue by kenzobenj** [rakovskij-stanislav/pyc_rules#1]
Not sure if this was intentional but your latest commit, 528b5ca7784353140485d9144d69e15ccac98c5b, deleted all of the rules in the file.

**Comment by rakovskij-stanislav** [comment]
Hello, @kenzobenj!

Thanks for noticing it. Updated the project, everything should works fine now.

**Comment by kenzobenj** [comment]
Thanks! And thanks for the great ruleset!
